#
# Copy this to config.yml and change the values
#

image_url: "http://dev.iron.io/images/iron_pony.png"
aws:
    access_key: "YOUR ACCESS KEY"
    secret_key: "YOUR SECRET KEY"
    s3_bucket_name: "BUCKET NAME"
operations:
    resize:
        width: 100
        height: 100
        destination: "resized_fname.jpg"
        format: 'jpg'
    generate_thumb:
         width: 50
         height: 50
         format: 'jpg'
         destination: "thumb_fname.jpg"
    sketch:
         destination: "sketch_fname.jpg"
         format: 'jpg'
    normalize:
         destination: "normalize_fname.jpg"
         format: 'jpg'
    charcoal_sketch:
         destination: "charcoal_sketch_fname.jpg"
         format: 'jpg'
    level:
         destination: "level_fname.jpg"
         black_point: 10
         white_point: 250
         gamma: 1.0
         format: 'jpg'
#    tile:
#         num_tiles_height: 3
#         num_tiles_width: 3
#         format: 'jpg'